site_name: Fogbed

theme:
  name: material
  palette:
    - scheme: 'default'
      media: '(prefers-color-scheme: light)'
      toggle:
        icon: 'material/lightbulb'
        name: "Switch to dark mode"
    - scheme: 'slate'
      media: '(prefers-color-scheme: dark)'
      toggle:
        icon: 'material/lightbulb-outline'
        name: 'Switch to light mode'
  features:
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.annotation
    - content.code.copy
  language: en

repo_name: larsid/fogbed
repo_url: https://github.com/larsid/fogbed/
edit_uri: ""

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/EsauM10
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/esau-mascarenhas/

copyright: |
  &copy; 2023 <a href="https://github.com/larsid/fogbed/"  target="_blank" rel="noopener">Fogbed</a>

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Introduction: 'index.md'
  
  - Usage:
    - QuickStart: 'quickstart.md'

  - Emulation:
    - Containers: 'containers.md'
    - Resource Models: 'resource_models.md'
    - Local Emulation: 'local_emulation.md'
    - Distributed Emulation: 'distributed_emulation.md'
    - Using Config Files: 'config_files.md'
    - Monitoring Metrics: 'monitoring_metrics.md'

  - Examples: 
    - Sensors: 'examples.md'
  - Plugins:
    - FogBesu: https://github.com/EsauM10/fogbesu
    - FogLedger: https://github.com/larsid/FogLedger
    - NetFL: https://github.com/larsid/netfl
   
